
[database]
# connections configuration
server = "localhost" # set by environment variables
user = "lfs" # set by environment variables
password = "lfs" # set by environment variables
verbose = false

database = "lfs" # set by environment variables
    [database.connectionPool]
       maxPoolSize = 10
       maxIdleConnections = 2
       maxLifetimeSeconds = 0
